version: '3.4'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_dba
      MYSQL_PASSWORD: Student1
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - frontend
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Student1
    ports:
      - 8080:80
    networks:
      - frontend
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    expose:
      - "1025"
    networks:
      - frontend
  httpbin:
    image: kennethreitz/httpbin:latest
    expose:
      - "80"
    networks:
     - frontend
    environment:
      - GUNICORN_CMD_ARGS=${GUNICORN_CMD_ARGS}
  wordpress:
    depends_on:
      - db
      - mailhog
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_dba
      WORDPRESS_DB_PASSWORD: Student1
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend

volumes:
  wordpress_data:
  db_data:
networks:
  frontend:
    driver: bridge


